### PR TITLE
Fix accessibility tests 👨🏻‍🔧

### LINKED ISSUE #1: Fix accessibility test
## The problem

After the migration from the Github Enterprise to open source we had to redo the yarn.lock.

This caused some accessibility tests failures.

Affected files:
`src/components/molecules/TextField/TextField.test.tsx`
`src/components/molecules/CheckboxField/CheckboxField.test.tsx`
`src/components/molecules/ZopaFooter/ZopaFooter.test.tsx`
`src/components/molecules/RadioField/RadioField.test.tsx`
`src/components/organisms/Accordion/AccordionHeader/AccordionHeader.test.tsx`
`src/components/molecules/DropdownFiltered/DropdownFiltered.test.tsx`

At the moment I commented/skip them to make the CI/CD work.

## The task
Investigate why are failing and fix them

### PR DESCRIPTION
**Pull request by lluia**
## Summary
It seems that the latest patch of `jest-axe`  throws unexpected errors around accessibility violations.

See [this issue](https://github.com/nickcolley/jest-axe/issues/56) for more context on why.

I pinned `jest-axe` to `3.1.0` and brought back the tests we were skipping.
I'll open an issue to bring back `jest-axe` to `^3.*.*` once they patch their patch 👍🏻 🚑 

## Issue
Fixes #1

### CODE REVIEW

**Comment by lluia** [comment]
Had a `rebase` issue, pushing new commit soon 😪

**Comment by poteirard** [comment]
1__yarn_dev__node_

I'm getting this error 🤷‍♂

**Comment by lluia** [comment]
@poteirard  ah I see many of the atoms are written in this fashion for some reason:
```jsx
const SAtom = styled.div`
  /* ... */
`
const Atom = props => <SAtom {...props} />;

export default Atom;
```
Doesn't look too good as it seems it's done to workaround the **Styleguidst** warning above? 🤔

I'll revert the changes of the file as they're out of the scope of this PR, but maybe we can open an issue to dive deep into this warning?

**Pull request merged**
