### PR TITLE
rename InputLabel to Label [TESTS FAILING]

### PR DESCRIPTION
**Pull request by endymion1818**
I had to use the `--no-verify` flag on commit because I don't know what these require:

```
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]
```

### CODE REVIEW

**Comment by thegrinder** [comment]
@endymion1818 we're using conventional commits, whenever you wanna commit run `yarn commit` instead of regular `git commit` and it's gonna walk you through the process

**Comment by poteirard** [comment]
Also probably you need to check the tests as one is failing: https://circleci.com/gh/zopaUK/react-components/410?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by endymion1818** [comment]
Thanks both! I'll update shortly.

**Comment by endymion1818** [comment]
Incorrect process; closing in favour of a PR that reflects the correct process for a contribution...

**Pull request closed without merging**
