### PR TITLE
Update README.md re issue #25

### PR DESCRIPTION
**Pull request by grabbeh**

### CODE REVIEW

**Comment by poteirard** [comment]
Thank you for this :) Would you mind changing your commit messages to follow this format: https://github.com/zopaUK/react-components/blob/master/CONTRIBUTING.md#git-commit-messages cheers! (I will add this check soon in the CI)

**Comment by grabbeh** [comment]
Heh, yes, sure - if I can figure out how to change the commit message. Is the easiest way if you reject this request and I submit another with the correct message?

**Comment by poteirard** [comment]
I think the best way is using `git rebase -i HEAD~2` to edit the commit messages. Check this: https://help.github.com/en/articles/changing-a-commit-message

**Pull request merged**
